apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack-hub-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snack-hub
  template:
    metadata:
      name: snack-hub
      labels:
        app: snack-hub
    spec:
      containers:
        - name: snack-hub
          image: ghcr.io/team-one-pos-tech/snack-hub:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          envFrom:
            - configMapRef:
                name: snack-hub-app-configmap
          livenessProbe:
            httpGet: 
              path: /api/Product/v1 #/health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: snack-hub-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snack-hub-app-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: snack-hub-app-service
spec:
  selector:
      app: snack-hub
  ports:
      - port: 8080
  type: LoadBalancer
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snack-hub-app-configmap
data:
  Storage__MongoDb__Host: "snack-hub-db-service"
  Storage__MongoDb__Port: "27017"
  Storage__MongoDb__UserName: "admin"
  Storage__MongoDb__Password: "admin"
  Storage__MongoDb__Database: "snackhub"  
  Auth__Lambda__SignUpUrl: "https://3qi3bn2xhg.execute-api.us-east-1.amazonaws.com/Prod/signup"  
  Auth__Lambda__SignInUrl: "https://3z9i9oglwh.execute-api.us-east-1.amazonaws.com/Prod/signIn"