apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack-hub-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snack-hub
  template:
    metadata:
      name: snack-hub
      labels:
        app: snack-hub
    spec:
      containers:
        - name: snack-hub
          image: kassiosan/snack-hub-app:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: Storage__MongoDb__Host
              value: snack-hub-db-service
            - name: Storage__MongoDb__Port
              value: "27017"
            - name: Storage__MongoDb__UserName
              value: admin
            - name: Storage__MongoDb__Password
              value: admin
            - name: Storage__MongoDb__Database
              value: snackhub

---
apiVersion: v1
kind: Service
metadata:
  name: snack-hub-app-service
spec:
  selector:
      app: snack-hub
  ports:
      - port: 8080
        nodePort: 30000
  type: NodePort