apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack-hub-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snack-hub
  template:
    metadata:
      name: snack-hub
      labels:
        app: snack-hub
    spec:
      containers:
        - name: snack-hub
          image: kassiosan/snack-hub-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: snack-hub-configmap
          livenessProbe:
            httpGet: 
              path: /api/Product/v1 #/health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: snack-hub-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snack-hub-app-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: snack-hub-app-service
spec:
  selector:
      app: snack-hub
  ports:
      - port: 8080
        nodePort: 30000
  type: NodePort
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snack-hub-configmap
data:
  Storage__MongoDb__Host: "snack-hub-db-service"
  Storage__MongoDb__Port: "27017"
  Storage__MongoDb__UserName: "admin"
  Storage__MongoDb__Password: "admin"
  Storage__MongoDb__Database: "snackhub"