apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack-hub-db-deployment
  labels:
    app: snack-hub-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snack-hub-db
  template:
    metadata:
      name: snack-hub-db
      labels:
        app: snack-hub-db
    spec:
      containers:
        - name: snack-hub-db
          image: mongo:latest
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: "462Mi"
              cpu: "2000m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
      
---
apiVersion: v1
kind: Service
metadata:
  name: snack-hub-db-service
spec:
  selector:
      app: snack-hub-db
  ports:
      - port: 27017
        nodePort: 30001
  type: NodePort