apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: snack-hub-db-stateful
spec:
  serviceName: snack-hub-db-service
  replicas: 1
  selector:
    matchLabels:
      app: snack-hub-db
  template:
    metadata:
      name: snack-hub-db
      labels:
        app: snack-hub-db
    spec:
      containers:
        - name: snack-hub-db
          image: mongo:latest
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: "462Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: snack-hub-db-configmap
          volumeMounts:
            - name: snack-hub-db-storage
              mountPath: /data/db
      volumes:
        - name: snack-hub-db-storage
          persistentVolumeClaim:
            claimName: snack-hub-db-pvc
              
---
apiVersion: v1
kind: Service
metadata:
  name: snack-hub-db-service
spec:
  selector:
      app: snack-hub-db
  ports:
      - port: 27017
        nodePort: 30001
  type: NodePort
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snack-hub-db-configmap
data:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin"
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snack-hub-db-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 1Gi
      