services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    
  snack-hub-app:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    container_name: snack-hub-api
    environment:
      - Storage:MongoDb:Host=mongodb
      - Storage:MongoDb:Port=27017
      - Storage:MongoDb:UserName=admin
      - Storage:MongoDb:Password=admin
      - Storage:MongoDb:Database=snackhub
      - Auth:Lambda:SignUpUrl=https://3qi3bn2xhg.execute-api.us-east-1.amazonaws.com/Prod/signup
      - Auth:Lambda:SignInUrl=https://3z9i9oglwh.execute-api.us-east-1.amazonaws.com/Prod/signIn
    ports:
      - "5000:8080"
    depends_on:
      - mongodb
    links:
      - mongodb