services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    
  snackhubapi:
    build:
      context: ../
      dockerfile: ../src/SnackHub.Api/Dockerfile
    container_name: snackhubapi
    environment:
      - Storage:MongoDb:Host=mongodb
      - Storage:MongoDb:Port=27017
      - Storage:MongoDb:UserName=admin
      - Storage:MongoDb:Password=admin
      - Storage:MongoDb:Database=snackhub
    ports:
      - "5000:8080"
    depends_on:
      - mongodb
    links:
      - mongodb