services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    
  snackhubapi:
    build:
      context: ../
      dockerfile: src/SnackHub.Api/Dockerfile
    container_name: snackhubapi
    restart: always
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dGVzdGU=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - Storage:MongoDb:Host=mongodb
      - Storage:MongoDb:Port=27017
      - Storage:MongoDb:UserName=admin
      - Storage:MongoDb:Password=admin
      - Storage:MongoDb:Database=snackhub
    ports:
      - "5002:80"
      - "5001:443"
    depends_on:
      - mongodb
    links:
      - mongodb
