name: CI Build
'on':
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore SnackHub.sln
      - name: Build
        run: dotnet build SnackHub.sln --no-restore
      - name: Test
        run: dotnet test SnackHub.sln --no-build --verbosity normal
  
  create-and-publish-image:
    needs: build-and-test
    permissions: write-all
    runs-on: self-hosted
    needs: build-and-test
    steps:     
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{github.actor}}'
          password: '${{secrets.GITHUB_TOKEN}}'
      - name: Build Image
        run: docker build -t ghcr.io/team-one-pos-tech/snack-hub -f ./src/SnackHub.Api/Dockerfile --target final .  --build-arg  "PASSWORD_ENV_SEEDED=Mf@7BF5uAN5rDBl7ZTCTqL%c&2ApeqCykva"
      - name: Push Image
        run: docker push ghcr.io/team-one-pos-tech/snack-hub

