name: CI Build
'on':
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  
  create-and-publish-image:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{github.actor}}'
          password: '${{secrets.GITHUB_TOKEN}}'
      - name: Build and Push SnackHub Image
        run: |
          docker build -t --tag ghcr.io/team-one-pos-tech/snack-hub:${GITHUB_SHA::7} -f ./deploy/Dockerfile .
          docker push ghcr.io/team-one-pos-tech/snack-hub:${GITHUB_SHA::7}
